### ISSUE TITLE
scope in auth flow

### ISSUE THREAD

**Issue by Garbolino** [yubozhao/meteor-accounts-instagram#6]
Is there any reason why you didn't include the scope in the auth request?

**Comment by Garbolino** [comment]
Sorry, it wasn't a problem with the code. To scope comments we need to request Instagram before.
Nice work and thanks again!

**Comment by yubozhao** [comment]
there is scope option. I will do a better job at doc on the next release.

**Comment by Garbolino** [comment]
Thanks mate.
I saw the scope option, but no matter what scope I set up, the request url includes always all of them
"...response_type=code&scope=basic+likes+relationships+comments&redirect_uri= ...'

**Comment by yubozhao** [comment]
@Garbolino  Let me check it very quick and get back to you.

**Comment by yubozhao** [comment]
I defined the scope at instagram_client.js lin 17

So  if you define the option that passed in has requestPermissions, it should works.  Let me know how that goes.  If that didn't works, I will makr this as bug and work on it.

Sorry about it.

**Comment by tantelyalbert** [comment]
I have an App instagram and when I generate token with scope=comments+likes, I don't get the equivalent of scope=comments but only basic and likes why please?
I have to request instagram before where please?I don't know if it is a new update because before that works well there is no matter like that
If someone have an idea,it's helpfull thank you so much

**Comment by yubozhao** [comment]
@tantelyalbert 

It is the same pattern as Meteor.loginWithFacebook or Meteor.loginWithGithub   , check docs.meteor.com for reference
